name: Daily Commit

on:
  schedule:
    # Run daily at 12:00 AM IST, which is 6:30 PM UTC (previous day)
    - cron: '30 18 * * *'
  workflow_dispatch: # Allows you to trigger the action manually

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "miryala.narayanareddy@straive.com"

    - name: Create a commit
      run: |
        # Create or modify a file to trigger a commit
        echo "Daily update: $(date)" >> daily_commit.txt
        git add daily_commit.txt
        git commit -m "Daily commit by GitHub Actions"
        git push