name: Daily Commit

on:
  # Run the first time within a few minutes after the workflow is added or updated
  push:
    branches:
      - main  # Change if your default branch is different

  # Run daily at 12:00 AM IST (which is 6:30 PM UTC the previous day)
  schedule:
    - cron: '30 18 * * *'

  # Allows manual trigger
  workflow_dispatch: 

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "miryala.narayanareddy@straive.com"

    - name: Create a commit
      run: |
        echo "Daily update: $(date)" >> daily_commit.txt
        git add daily_commit.txt
        git commit -m "Daily commit by GitHub Actions"
        git push